"""Create All the Tables

Revision ID: 17340d01e2f9
Revises: 
Create Date: 2026-09-16 20:58:50.716309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17340d01e2f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporates',
    sa.Column('corporate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corporate_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('contacts', sa.String(length=100), nullable=False),
    sa.Column('wallet_type', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('corporate_id')
    )
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=50), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_id'), ['id'], unique=False)

    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mpesa_paybill', sa.String(length=50), nullable=False),
    sa.Column('mpesa_account_prefix', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('bank_account_name', sa.String(length=100), nullable=False),
    sa.Column('bank_account_number', sa.String(length=50), nullable=False),
    sa.Column('bank_branch', sa.String(length=100), nullable=False),
    sa.Column('kra_pin', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_address', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_types',
    sa.Column('rate_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rate_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('corporate_id', sa.Integer(), nullable=True),
    sa.Column('otp_code', sa.String(length=4), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('vat', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'PENDING', 'OVERDUE'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('Bank_name', sa.String(length=100), nullable=True),
    sa.Column('Paybill_number', sa.String(length=100), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('decline_reason', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_table('rates',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('rate_type_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['rate_type_id'], ['rate_types.rate_type_id'], ),
    sa.PrimaryKeyConstraint('rate_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('staff_number', sa.String(length=50), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('rides_allocated', sa.Integer(), nullable=True),
    sa.Column('rides_used', sa.Integer(), nullable=True),
    sa.Column('max_fare_per_ride', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('staff_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wallet',
    sa.Column('wallet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=True),
    sa.Column('wallet_type', sa.Enum('CORPORATE_FUNDED', 'PLATFORM_FUNDED', 'PLATFORM_REVENUE'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_table('ride_counters',
    sa.Column('counter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('cumulative_no_of_rides', sa.Integer(), nullable=False),
    sa.Column('cumulative_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('counter_id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('ride_requests',
    sa.Column('ride_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('matatu_identifier', sa.String(length=100), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=True),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('total_fare', sa.Float(), nullable=True),
    sa.Column('matatu_payout', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('ride_id')
    )
    op.create_table('gateway_payouts',
    sa.Column('payout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('target_identifier', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('amount_sent', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED'), nullable=False),
    sa.Column('gateway_reference', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.ride_id'], ),
    sa.PrimaryKeyConstraint('payout_id')
    )
    op.create_table('invoice_line_items',
    sa.Column('line_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.ride_id'], ),
    sa.PrimaryKeyConstraint('line_item_id')
    )
    op.create_table('ledger_entries',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('TRIP_DEDUCTION', 'PLATFORM_TOPUP', 'CORPORATE_TOPUP', 'INVOICE_PAYMENT', 'TRIP_REVERSAL', 'COMMISSION_CHARGE', 'INVOICE_REVERSAL'), nullable=False),
    sa.Column('transaction_class', sa.Enum('Debit', 'Credit'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.ride_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('platform_revenue',
    sa.Column('revenue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('revenue_type', sa.Enum('COMMISSION', 'VAT'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.ride_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('revenue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_revenue')
    op.drop_table('ledger_entries')
    op.drop_table('invoice_line_items')
    op.drop_table('gateway_payouts')
    op.drop_table('ride_requests')
    op.drop_table('ride_counters')
    op.drop_table('wallet')
    op.drop_table('staff')
    op.drop_table('rates')
    op.drop_table('invoice')
    op.drop_table('users')
    op.drop_table('rate_types')
    op.drop_table('platform_settings')
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'))

    op.drop_table('mpesa_transactions')
    op.drop_table('corporates')
    # ### end Alembic commands ###
