"""Add Invoice, Payment, PlatformRevenue models

Revision ID: 2ab610f743ed
Revises: b5812e80fa73
Create Date: 2026-07-28 15:38:32.902595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab610f743ed'
down_revision = 'b5812e80fa73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'OVERDUE'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_table('platform_revenue',
    sa.Column('revenue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('revenue_type', sa.Enum('COMMISSION', 'VAT', 'PLATFORM_FEE'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.ride_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('revenue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_revenue')
    op.drop_table('payment')
    op.drop_table('invoice')
    # ### end Alembic commands ###
