"""Add the INVOICE_REVERSAL on ledger entry transaction types

Revision ID: 4686cd648446
Revises: 494aa18b3a7d
Create Date: 2026-08-27 10:35:45.886409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4686cd648446'
down_revision = '494aa18b3a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=mysql.ENUM('TRIP_DEDUCTION', 'PLATFORM_TOPUP', 'CORPORATE_TOPUP', 'INVOICE_PAYMENT', 'TRIP_REVERSAL', 'COMMISSION_CHARGE'),
               type_=sa.Enum('TRIP_DEDUCTION', 'PLATFORM_TOPUP', 'CORPORATE_TOPUP', 'INVOICE_PAYMENT', 'TRIP_REVERSAL', 'COMMISSION_CHARGE', 'INVOICE_REVERSAL'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('TRIP_DEDUCTION', 'PLATFORM_TOPUP', 'CORPORATE_TOPUP', 'INVOICE_PAYMENT', 'TRIP_REVERSAL', 'COMMISSION_CHARGE', 'INVOICE_REVERSAL'),
               type_=mysql.ENUM('TRIP_DEDUCTION', 'PLATFORM_TOPUP', 'CORPORATE_TOPUP', 'INVOICE_PAYMENT', 'TRIP_REVERSAL', 'COMMISSION_CHARGE'),
               existing_nullable=False)

    # ### end Alembic commands ###
