"""add decline_reason

Revision ID: 494aa18b3a7d
Revises: a7f9677830b5
Create Date: 2026-08-27 09:28:11.130028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494aa18b3a7d'
down_revision = 'a7f9677830b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decline_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('decline_reason')

    # ### end Alembic commands ###
