""" added basefare,total.commiosn,vat

Revision ID: 5638ffdd0b83
Revises: e43399f3bd7d
Create Date: 2026-08-22 22:48:33.703690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5638ffdd0b83'
down_revision = 'e43399f3bd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_fare', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('commision', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('vat', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('vat')
        batch_op.drop_column('commision')
        batch_op.drop_column('base_fare')

    # ### end Alembic commands ###
