"""Add reversed_by and reversed_at columns in the Invoice table

Revision ID: 64c67fed8bc4
Revises: 4686cd648446
Create Date: 2026-08-27 13:33:09.891742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c67fed8bc4'
down_revision = '4686cd648446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reversed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reversed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reversed_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reversed_at')
        batch_op.drop_column('reversed_by')

    # ### end Alembic commands ###
