"""Add wallet table

Revision ID: 7cc88308f5e0
Revises: 
Create Date: 2026-07-20 18:47:53.212457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc88308f5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('wallet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=True),
    sa.Column('wallet_type', sa.Enum('CORPORATE_FUNDED', 'PLATFORM_ALLOCATED', 'PLATFORM_REVENUE', name='wallettype'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
