"""Add account_reference to gateway_payouts

Revision ID: 80236c09adbc
Revises: 496af0a65c87
Create Date: 2026-08-31 18:13:43.152633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80236c09adbc'
down_revision = '496af0a65c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gateway_payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_reference', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gateway_payouts', schema=None) as batch_op:
        batch_op.drop_column('account_reference')

    # ### end Alembic commands ###
