"""remove max_rides and max_amount columns

Revision ID: 82807ee2bd62
Revises: 0300bb9deb2f
Create Date: 2026-07-23 18:29:39.612082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82807ee2bd62'
down_revision = '0300bb9deb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False))
        batch_op.drop_column('max_rides')
        batch_op.drop_column('max_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_amount', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('max_rides', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
