"""Add max_rides and max_amount to staff

Revision ID: 8d462a5bec62
Revises: 9775cd5d642f
Create Date: 2026-07-21 19:02:01.610467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d462a5bec62'
down_revision = '9775cd5d642f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_rides', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('max_amount')
        batch_op.drop_column('max_rides')

    # ### end Alembic commands ###
