"""Create ledger_entries table

Revision ID: a64f99b8c80d
Revises: 7cc88308f5e0
Create Date: 2026-07-20 23:51:05.069831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64f99b8c80d'
down_revision = '7cc88308f5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('TRIP_DEDUCTION', 'TOPUP', 'INVOICE_PAYMENT', 'TRIP_REVERSAL', 'COMMISSION_CHARGE'), nullable=False),
    sa.Column('transaction_class', sa.Enum('Debit', 'Credit'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.ride_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
