""" nullable true condition added

Revision ID: a7f9677830b5
Revises: 5638ffdd0b83
Create Date: 2026-08-23 21:22:36.030222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7f9677830b5'
down_revision = '5638ffdd0b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('account_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('Bank_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('Bank_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('account_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
