"""drop paybill_number and account_number from gateway_payouts

Revision ID: b3e5c42714a6
Revises: 2ddff76a7848
Create Date: 2026-08-31 18:39:50.956258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3e5c42714a6'
down_revision = '2ddff76a7848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gateway_payouts', schema=None) as batch_op:
        batch_op.drop_column('account_number')
        batch_op.drop_column('paybill_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gateway_payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paybill_number', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_number', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
