"""Added ride_counters table

Revision ID: b5812e80fa73
Revises: 04e2af9c4801
Create Date: 2026-07-24 14:34:25.435296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5812e80fa73'
down_revision = '04e2af9c4801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_counters',
    sa.Column('counter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('cumulative_no_of_rides', sa.Integer(), nullable=False),
    sa.Column('cumulative_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('counter_id'),
    sa.UniqueConstraint('staff_id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               nullable=True)

    op.drop_table('ride_counters')
    # ### end Alembic commands ###
