"""Add OTP fields to User model

Revision ID: c36f186da244
Revises: 2ab610f743ed
Create Date: 2026-07-30 16:34:28.082398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36f186da244'
down_revision = '2ab610f743ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
