"""initial migration

Revision ID: c3ceef204a3c
Revises: 
Create Date: 2026-07-22 11:32:17.496162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3ceef204a3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('TRIP_DEDUCTION', 'PLATFORM_TOPUP', 'CORPORATE_TOPUP', 'INVOICE_PAYMENT', 'TRIP_REVERSAL', 'COMMISSION_CHARGE'), nullable=False),
    sa.Column('transaction_class', sa.Enum('Debit', 'Credit'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.corporate_id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.ride_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.alter_column('wallet_type',
               existing_type=mysql.ENUM('CORPORATE_FUNDED', 'PLATFORM_ALLOCATED', 'PLATFORM_REVENUE'),
               type_=sa.Enum('CORPORATE_FUNDED', 'PLATFORM_FUNDED', 'PLATFORM_REVENUE'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.alter_column('wallet_type',
               existing_type=sa.Enum('CORPORATE_FUNDED', 'PLATFORM_FUNDED', 'PLATFORM_REVENUE'),
               type_=mysql.ENUM('CORPORATE_FUNDED', 'PLATFORM_ALLOCATED', 'PLATFORM_REVENUE'),
               existing_nullable=False)

    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
