"""Make corporate_id nullable for staff

Revision ID: db8b9c002fde
Revises: c36f186da244
Create Date: 2026-08-11 15:59:08.739020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db8b9c002fde'
down_revision = 'c36f186da244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('corporate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('corporate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
