"""Initial migration

Revision ID: e43399f3bd7d
Revises: 
Create Date: 2026-08-22 22:08:59.875724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e43399f3bd7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['transaction_reference'])

    with op.batch_alter_table('platform_revenue', schema=None) as batch_op:
        batch_op.alter_column('revenue_type',
               existing_type=mysql.ENUM('COMMISSION', 'VAT', 'PLATFORM_FEE'),
               type_=sa.Enum('COMMISSION', 'VAT'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_revenue', schema=None) as batch_op:
        batch_op.alter_column('revenue_type',
               existing_type=sa.Enum('COMMISSION', 'VAT'),
               type_=mysql.ENUM('COMMISSION', 'VAT', 'PLATFORM_FEE'),
               existing_nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
