"""Make paid_at nullable

Revision ID: f88b2b890144
Revises: 64c67fed8bc4
Create Date: 2026-08-27 13:44:30.297392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f88b2b890144'
down_revision = '64c67fed8bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission', sa.Float(), nullable=False))
        batch_op.drop_column('commision')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commision', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('commission')

    # ### end Alembic commands ###
